apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: voting-app
  labels:
    app: mongo-db
spec:
  clusterIP: None  # Headless service
  selector:
    app: mongo-db
  ports:
    - port: 27017
      targetPort: 27017
